### PR TITLE
Add customizable background color param

### PR DESCRIPTION
**Pull request by hyouuu**
As well as changing blurStyle param from optional to required as we always provide a default value, and format the init calls.

The initiative is that a friend said he felt the gray blurred background feels like coming from nowhere and somewhat distracting, so I'm customizing my app to use black background just like how most photo viewers behave

### CODE REVIEW

**Comment by JanGorman** [comment]
I was away on vacation – sorry for the delay. I'll take a look at this later today

**Comment by JanGorman** [comment]
@hyouuu So I finally got round to looking at this. I like the idea but really the background color and background blur are mutually exclusive options, i.e. when you set a color you don't see or should set a blur. The initialisers should reflect that as otherwise they suggest that you can set a coloured blur.

I'd modify this to create separate convenience initialisers that make this explicit and then also make sure that if a colour is set, no blur is applied to save the system from doing work that's not needed. Then we're good to go.

**Comment by hyouuu** [comment]
Makes sense - I'll change it when have a chance; feel free to change on top of my changes if you get free time ;)

**Comment by hyouuu** [comment]
Awesome thanks!!

**Pull request closed without merging**
