### PR TITLE
Added AgrumeDataSource implementation

### PR DESCRIPTION
**Pull request by mcrakhman**
Please note that I haven't provided an example of usage, though I have tested the implementation in my own project (an application loading images from dropbox, it loads thumbnails and upon a person tapping on a thumbnail an image is loaded and shown in Agrume).

I would be happy to add an example, though it seems it will require importing of the third party library which downloads something (e.g. Dropbox), otherwise we can use URL's Agrume init, no need for data source. And using any third party library will require a bigger amount of code, additional explanations etc. 

I can think of an example project which enables a user to scroll through images in a dropbox folder (collection view with small thumbnails (e.g. 64*64)) and download/show them in Agrume upon user tapping a cell via data source. Please tell if you think that it will be a good idea to create something like that.

Please don't hesitate to contact me if something needs to be changed/not working or otherwise :smiley: Thanks again for the great library!

### CODE REVIEW

**Comment by JanGorman** [comment]
Thanks for the addition – really appreciate it! :clap: 
I'll add the data source to the documentation, maybe later do an example.

**Comment by vpanghal** [comment]
@mcrakhman  This is great addition to Agrume. I was trying this out in my project and I find that indexPathsForVisibleItems in Agrume collection is not being updated with item being displayed.
And UI keep displaying spinner.

Do you know why it is not being updated?


`

               dataSource.imageForIndex(index) { [weak self] image in
                print(indexPath)
                print(collectionView.indexPathsForVisibleItems())
                if collectionView.indexPathsForVisibleItems().contains(indexPath) { <<<<<<< This check is failing

					cell.image = image
					self?.spinner.alpha = 0
				}
			}
`


Output
`

    <NSIndexPath: 0xc000000000000016> {length = 2, path = 0 - 0}
    []

    <NSIndexPath: 0xc000000000200016> {length = 2, path = 0 - 1}
    [<NSIndexPath: 0xc000000000000016> {length = 2, path = 0 - 0}]

    <NSIndexPath: 0xc000000000400016> {length = 2, path = 0 - 2}
    [<NSIndexPath: 0xc000000000200016> {length = 2, path = 0 - 1}]

`

**Comment by mcrakhman** [comment]
Thanks! Will check this and return back.

**Comment by mcrakhman** [comment]
I have checked the issue. Works alright when dataSource uses async downloads in `imageForIndex`, though it indeed fails when the image is transferred immediately. In these cases it looks like collectionView.indexPathsForVisibleItems() doesn't get updated (so the check always fails), but `dispatch_async` seems to fix the issue. See code below.
```Swift
dataSource.imageForIndex(index) { [weak self] image in
	dispatch_async(dispatch_get_main_queue()) { 
		if collectionView.indexPathsForVisibleItems().contains(indexPath) {
			cell.image = image
			self?.spinner.alpha = 0
		}
	}
}
```
Please tell if that solves your problem, then I will make an updated pull request. If that does not solve the problem, please describe the issue in greater detail (i.e provide your implementation of the dataSource methods).

Thanks again!

**Comment by vpanghal** [comment]
That did work like a charm! Thanks @mcrakhman

**Pull request merged**
