### PR TITLE
Add Package.swift

### LINKED ISSUE #162: Support Swift packager manager
Are you planning to support SPM??

### PR DESCRIPTION
**Pull request by sschizas**
This PR adds Package.swift to make Agrume available via SPM.

Resolves #162

How it was tested

I tested it from my own fork. :smiley:

### CODE REVIEW

**Comment by JanGorman** [comment]
Very cool, thanks. Could you fix the two issues that SwiftLint is complaining about in the comment and then it should be good to go 🎉

**Comment by sschizas** [comment]
@JanGorman done 👍

**Comment by sschizas** [comment]
@JanGorman you need to create a new release in order the Package.swift to take effect.

**Comment by JanGorman** [comment]
Yes, Sorry that I didn't get around to doing that anymore yesterday. Will create it now

**Pull request merged**
