### PR TITLE
Add long press gesture & updateImage func

### PR DESCRIPTION
**Pull request by hyouuu**
So client can e.g. show an action sheet upon long press.

Added updateImage function so we could refresh Agrume cells after the image got changed e.g. from cropping it

### CODE REVIEW

**Comment by JanGorman** [comment]
I'm making some fixes. This update image code doesn't actually work because AgrumeImage is a struct

**Comment by hyouuu** [comment]
Interesting - it seems to work for me when updating url

**Comment by JanGorman** [comment]
URL is var, image was let. It's changed. But it didn't even compile that way :( I made it 2 methods because updating both image and URL is a no-op and splitting this into two separate methods makes the distinction clear.

**Comment by hyouuu** [comment]
Cool - I thought about splitting into two, but saw the init() had both in one place so copied that pattern, but now found that that's the private version of the init :p

**Comment by Alexookah** [comment]
@hyouuu 
It would be cool if you added some general function what the OnLongPressFunction could be in the documentation with an example.
Some ActionSheet with some options to save the image?

**Comment by hyouuu** [comment]
Good idea! Will do when I get free time :)

**Comment by Alexookah** [comment]
https://github.com/JanGorman/Agrume/pull/151
i did something like this
Did you do something similar or something different?

**Pull request merged**
